export const ActionTypes = {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    TODOS_FETCH_REQUESTED: 'TODOS_FETCH_REQUESTED',
    TODOS_FETCH_SUCCEEDED: 'TODOS_FETCH_SUCCEEDED',
    TODOS_FETCH_FAILED: 'TODOS_FETCH_FAILED',
}